### ISSUE TITLE
make a local copy of the start page

### ISSUE THREAD

**Issue by HotCoffeMug** [PrettyCoffee/yet-another-generic-startpage#8]
hi, i tried to save the repository to my documents folder since my internet is slow, but when i open the index.html its a blank page, what file i have to open to display the page keeping my bookmark?

**Comment by PrettyCoffee** [comment]
Hello :)
If you want a local copy, I recommend to use the Mini-YAGS export. You can find it in the settings:

![image](https://user-images.githubusercontent.com/66521452/195606381-5a463bd7-85a0-4e38-94e8-e88295c17316.png)

After extracting the files from the zip, you can use the `index.html` from there.

However. if you don't want to use the Mini-YAGS export for any reason, you will have to use the `gh-pages` branch instead of the `master`. Download the branch files to your computer and open the `index.html`, that should work just fine :)

If you need any help on how to do that, let me know and I can give you more instructions. 👍

**Comment by HotCoffeMug** [comment]
thanks you so much
